# -*- mode: ruby -*-
# vi: set ft=ruby sw=2 :

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.host = "localhost"
    libvirt.uri = "qemu:///system"
  end
end
